---
- name: The update role applies to all servers
  hosts: all
  become: true
  
  roles:
    - updates

- name : Servers that should have docker ce installed
  hosts: dockerceServers
  become: true

  roles:
    - role: dockerce
      
