---
- name: "Updating apt repo and cache on all Debian/Ubuntu servers"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: "Wait for sudo"
  shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- name: "Upgrading all packages on Debian/Ubuntu servers"
  apt: upgrade=dist force_apt_get=yes

- name: "Installing ntp"
  apt:
    pkg:
      - ntp
    state: latest

- name: "Making sure the ntp.conf file is correct"
  copy:
    src: ./ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root

- name: "Restarting ntp"
  service:
    name: ntp
    state: started
    enabled: yes

