---
- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  ansible.builtin.runas:
    become_user: root
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Update all packages to their latest version
  ansible.builtin.runas:
    become_user: root
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Remove useless packages from the cache
  ansible.builtin.runas:
  become_user: root
  ansible.builtin.apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  ansible.builtin.runas:
  become_user: root
  ansible.builtin.apt:
    autoremove: yes
