---
- name: "Updating managed infrastructure"
  hosts: all
  become: true
  user: ansible
  connection: ssh

  tasks:
  - name: "Installing Chrony"
    yum:
      name: 
        - chrony
      state: latest

  - name: "Making sure the chrony.conf file is correct"
    copy:
      src: ./chrony.conf
      dest: /etc/chrony.conf
      owner: root
      group: root

  - name: "Restarting chrony"
    service:
      name: chronyd
      state: started
      enabled: yes
    
  - name: "Upgrading all packages on RHEL"
    yum: name=* state=latest
