---
- name: "Upgrading all packages on RHEL"
  become: yes
  yum: name=* state=latest

- name: "Installing Chrony"
  become: true
  yum:
    name: 
      - chrony
    state: latest

- name: "Making sure the chrony.conf file is correct"
  become: true
  copy:
    src: ./chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root

- name: "Restarting chrony"
  become: true
  service:
    name: chronyd
    state: started
    enabled: yes
  
