---
  - name: "Updating managed infrastructure"
    hosts: all
    become: true
    user: ansible
    connection: ssh
  
    tasks:

    - name: Install ntp
      apt:
        pkg:
          - ntp
        state: latest
      when: ansible_facts['os_family'] == 'Debian'
  
    - name: Install chrony on RedHat
      yum:
        name: 
          - chrony
        state: latest
      when: ansible_facts['os_family'] == 'RedHat'
 
    - name: Install chrony on Suse
      zypper:
        name:
          - chrony
        state: latest
      when: ansible_facts['os_family'] == 'Suse'
  
    - name: "Make sure the chrony.conf file is correct"
      copy:
        src: ./chrony.conf
        dest: /etc/chrony.conf
        owner: root
        group: root
      when: ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Suse'
 
    - name: restart ntp
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == 'Debian'
  
    - name: restart chrony
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      when: ansible_facts['os_family'] == 'Debian'

    - name: Upgrade all packages on Debian/Ubuntu servers
      apt: upgrade=dist force_apt_get=yes
      when: ansible_facts['os_family'] == 'Debian'
      
    - name: upgrade all packages on CentOS
      yum: name=* state=latest
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Update all packages on OpenSUSE/SUSE Linux
      zypper: name=* state=latest
      when: ansible_facts['os_family'] == 'Suse'
